def print_menu():
	print("Corner                           Edge                                    Corner")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                              This is a test                                   ")
	print("                                                                               ")
	print("                                                                           Edge")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("Edge                                                                           ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("                                                                               ")
	print("Corner                                Edge                               Corner")