def getPlugboard():
    tempDic = {
        "!":"H",
        "#":"p",  #  #-this repesents " 
        "/":"S",  #  /-this repesents the comma
        "-":"x",
        ".":";",
        ";":"o",
        "?":"X",
        "A":"P",
        "B":"G",
        "C":"M",
        "D":"#",
        "E":"J",
        "F":"!",
        "G":"F",
        "H":"/",
        "I":"i",
        "J":"y",
        "K":"W",
        "L":"N",
        "M":"K",
        "N":"n",
        "O":"O",
        "P":"j",
        "Q":"D",
        "R":"d",
        "S":"V",
        "T":"s",
        "U":"?",
        "V":"Y",
        "W":"U",
        "X":"v",
        "Y":"A",
        "Z":"a",
        "a":"c",
        "b":"E",
        "c":"C",
        "d":".",
        "e":"q",
        "f":"l",
        "g":"f",
        "h":"Q",
        "i":"B",
        "j":"R",
        "k":"u",
        "l":"w",
        "m":"-",
        "n":"T",
        "o":"m",
        "p":"r",
        "q":"e",
        "r":"Z",
        "s":"b",
        "t":"I",
        "u":"z",
        "v":"L",
        "w":"k",
        "x":"h",
        "y":"t",
        "z":"g"}
    return tempDic
   
